name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'
        channel: 'stable'
        
    - name: Enable web support
      run: flutter config --enable-web
        
    - name: Clean
      run: flutter clean
        
    - name: Get dependencies with override
      run: |
        flutter pub get
        flutter pub deps
      
    - name: Build web
      run: flutter build web --release --base-href "/ai_paralegal/" --web-renderer canvaskit
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build/web
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
